### ISSUE TITLE
v3.0.3 breaks production build

### ISSUE THREAD

**Issue by pranavjindal999** [MiguelCastillo/load-js#26] opened 2018-09-20 06:42 UTC
I use webpack to build my app (vue-cli-v3).
Everything was working fine till v3.0.2 until I upgraded to v3.0.3.

### Error Screenshot:
![image](https://user-images.githubusercontent.com/5094327/45800301-1c5de300-bcce-11e8-9425-6e570816e2c4.png)

![image](https://user-images.githubusercontent.com/5094327/45800338-3e576580-bcce-11e8-80ab-b8aa862ed7b4.png)

**Comment by MiguelCastillo** [comment] 2018-09-20 22:42
oh no!!  Let me take a closer look.  Thanks a lot for raising the issue.

**Comment by MiguelCastillo** [comment] 2018-09-22 02:06
@pranavjindal999 do you have a sample test I can reproduce this with?  I am not able to reproduce the issue... The looks like a trace from devtools in Chrome, is that right?

**Comment by pranavjindal999** [comment] 2018-09-22 07:20
@MiguelCastillo 
Yes that is from chrome dev tools.

Here is the bug repro branch:
https://github.com/pranavjindal999/Youtube-Material/tree/load-js-bug-repro

#### Steps:
- clone and checkout `load-js-bug-repro`
- yarn build
- run server in `dist` directory

**You'll get the same error.**

#### Steps to fix:
- Downgrade load-js version to 3.0.2
- yarn build
- run server in `dist` directory

**Works great without any issue.**

**Comment by MiguelCastillo** [comment] 2018-09-22 13:43
@pranavjindal999 by run server in dist you mean `npm run serve`?

**Comment by pranavjindal999** [comment] 2018-09-22 15:11
@MiguelCastillo 
 Nope. That command is for dev server.

You need to make your own server. May be use this dead-simple module:

https://www.npmjs.com/package/@vivaxy/here (install it globally on your system)

**Comment by MiguelCastillo** [comment] 2019-02-14 14:49
@pranavjindal999 I havent had cycles to take a closer look at this issue and I havent seen anyone else report this problem.  I am going to close this issue but I welcome PRs!  Thank you kindly for logging this issue.

**Closed as completed by MiguelCastillo** 2019-02-14 14:49 UTC

**Comment by pranavjindal999** [comment] 2019-02-14 17:38
Well I recently made another project with vue-cli and faced the same problem.
So I'm just using v3.0.2.
